name: Deploy to VPS

on:
  push:
    branches:
      - main   # Only run on main branch pushes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ls
            cd /testing/githubworkflow/   # your app folder on VPS
            git pull origin main
            npm install
            npm run build
            pm2 restart myapp
